## 线性代数

标量只有一个元素的张量表示

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

你可以将向量视为标量值组成的列表

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [3]:
x[3]

tensor(3)

访问张量的长度

In [4]:
len(x)

4

只有一个轴的张量，形状只有一个元素

In [5]:
x.shape

torch.Size([4])

通过指定两个分量 m 和 n 来创建一个形状为 m × n 的矩阵

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [7]:
A.T
# 行列互换

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵(symmetric matrix) $A$ 等于其转置：$A=A^T$

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0 , 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X
# X 表示一个三维的张量
# 可以理解为在 1 个三维张量中，有 2 个二维矩阵，每个二维矩阵有 3 个向量，每个向量有 4 个标量
# 也就是说这表示这一个三维张量中有 2 个 3 行 4 列的矩阵
# 列是倒数第一维，行是倒数第二维，面是第一维

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同的张量

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将 A 的一个副本分配给 B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为 哈达玛积 (Hadamard product),数学符号为 ⊙

In [12]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, a * X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [14]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()
# sum() 方法能对所有元素进行求和，结果永远是个标量

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [15]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

**指定求和汇总张量的轴**

In [16]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [17]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [18]:
A = torch.arange(20*2).reshape(2, 5, 4)
# 重塑成一个三维张量
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [19]:
A_sum_axis0 = A.sum(axis=0)
# 对重塑之后的三维张量对第一个维度进行求和，实际上就是把两个 5 × 4 的矩阵按元素进行相加
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [20]:
A_sum_axis1 = A.sum(axis=1)
# 对重塑之后的三维张量对第二个维度进行求和，实际上就是把两个 5 × 4 的矩阵各自压缩这个 "5" ，也就是把各种的矩阵的行进行按元素相加
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [23]:
A_sum_axis2 = A.sum(axis=2)
# 对重塑之后的三维张量对第三个维度进行求和，实际上就是把两个 5 × 4 的矩阵各自压缩这个 "4" ，也就是把各种的矩阵的列进行按元素相加
A_sum_axis2, A_sum_axis2.shape

(tensor([[  6,  22,  38,  54,  70],
         [ 86, 102, 118, 134, 150]]),
 torch.Size([2, 5]))

In [26]:
# 也可以对两个维度同时进行求和
A.sum(axis=[0, 1]) # Same as `A.sum()`
# 实际上可以理解为先按 2 个 5 × 4 的矩阵进行按元素相“压”之后，再继续“压”行
# A.sum(axis=[0, 1]).shape --> torch,Size([4])

tensor([180, 190, 200, 210])

一个与求和相关的量是 平均值（mean 或 average）

In [34]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A, A.sum(), A.mean(), A.sum() / A.numel()
# 求均值要求数据类型必须为浮点数
# A.mean() 其实就是 A.sum() 张量所有元素的值总和除以元素总数 = A。sum() / 20 = 190/20 = 9.5
# A.numel() 方法可以直接返回 int 类型的元素个数，所以 A.mean()的值就是 A.sum() / A.numel

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(190.),
 tensor(9.5000),
 tensor(9.5000))

In [35]:
# 同样 mean() 方法还可以根据维度进行求值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]
# 对第一个维度（别忘了 axis=0 第一个维度，axis=1 第二个维度）进行求均值，实际上就是把 5 行压缩，求均值
# 同理 A.mean(axis=0) 和 A.sum(axis=0) / A.shape[0] 效果相当

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

计算总和或均值时保持轴数不变

In [39]:
sum_A = A.sum(axis=1)
sum_A

tensor([ 6., 22., 38., 54., 70.])

In [40]:
sum_A_keep = A.sum(axis=1, keepdims=True)
# 本来对第二个维度进行求和的时候，也就是要压列变行，但是我可以选择保持轴数不变，这样做的目的是可以使用广播机制。
sum_A_keep

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播将 A 除以 sum_A

In [43]:
# 如果上面没有使用 keepdims=True 那就少了一个维度，那么下面就不可以进行广播机制了
A / sum_A_keep

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

某个轴计算 A 元素的累计总和

In [47]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [49]:
A.cumsum(axis=0)
# 实际上就是按第一维度进行元素求和，就是将每一行进行累加，“累加与加不同”，“累加”不会改变维度

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

点积是相同元素的按元素乘积的和

In [50]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [51]:
torch.sum(x * y)

tensor(6.)

矩阵向量积 $AX$ 是一个长度为 m 的列向量，其 $i^{th}$ 元素是点积 $a_{i}^TX$

In [52]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法 $AB$ 看做是简单地执行 m 次矩阵-向量积，并将结果拼接在一起，形成一个 $n×m$ 矩阵

In [54]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

$L_2$ 范数是向量元素平方和的平方根：$\|\mathbf{x}\|_{2}=\sqrt{\sum_{i=1}^{n} x_{i}^{2}}$

In [55]:
u  = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$ 范数，它表示为向量元素的绝对值之和：$\|\mathbf{x}\|_{1}=\sum_{i=1}^{n}\left|x_{i}\right|$

In [57]:
torch.abs(u).sum()

tensor(7.)

矩阵的 弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根：$\|\mathbf{X}\|_{F}=\sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} x_{i j}^{2}}$
> $L_2$ 范数是针对向量而言， $F$ 范数是针对矩阵而言的

In [59]:
torch.norm(torch.ones((4, 9)))

tensor(6.)