## 用神经网路实现手写识别
+ 数据集：ex3data1.mat
+ 参数：ex3weights.mat （已经训练好的权重参数）

![image.png](<https://i.typlog.com/tanxy/8336871808_4946.png>)

In [1]:
import numpy as np
import scipy.io as sio

In [2]:
data = sio.loadmat('ex3data1.mat')
raw_X = data['X']
raw_y = data['y']

In [3]:
X = np.insert(raw_X, 0, values=1, axis=1) # 添加偏置项
X.shape

(5000, 401)

In [4]:
y = raw_y.flatten() # 使用 flatten() 函数将 y 这个二维数组降低为 一维数组，为了最后算准确率比较方便
y.shape

(5000,)

In [16]:
y

array([10, 10, 10, ...,  9,  9,  9], dtype=uint8)

In [6]:
theta = sio.loadmat('ex3weights.mat') # 导入权重参数，这是个字典
theta.keys() # 查看其键

dict_keys(['__header__', '__version__', '__globals__', 'Theta1', 'Theta2'])

In [7]:
theta1 = theta['Theta1'] # 从权重参数数据集中获取 Theta1 ，这是输入层到隐藏层之间的权重参数
theta2 =theta['Theta2'] #从权重参数数据集中获取额 Theta2 , 这隐藏层到输出层之间的权重参数

theta1.shape, theta2.shape

((25, 401), (10, 26))

## 开始实现整个前向传播的过程

In [8]:
# 定义 sigmoid 函数（使用的激活函数是 sigmoid 函数）
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [30]:
a1 = X # 第一层输入特征

In [9]:
z2 = X @ theta1.T # 因为此时 X 的 shape 为（5000， 401） 而 theta1 的 shape 为 （25, 401） ，为了相乘，则维度要匹配，所以 theta1,T
a2 = sigmoid(z2) # 隐藏层的输入特征

In [32]:
a2.shape

(5000, 25)

In [10]:
a2 = np.insert(a2, 0, values=1, axis=1) # 为 a2 添加一个偏置项
a2.shape

(5000, 26)

In [11]:
z3 = a2 @theta2.T # 类似上面的过程
a3  = sigmoid(z3) # a3 输出的值代表每一个样本属于某个类别的概率

In [35]:
a3.shape

(5000, 10)

In [12]:
a3

array([[1.12661530e-04, 1.74127856e-03, 2.52696959e-03, ...,
        4.01468105e-04, 6.48072305e-03, 9.95734012e-01],
       [4.79026796e-04, 2.41495958e-03, 3.44755685e-03, ...,
        2.39107046e-03, 1.97025086e-03, 9.95696931e-01],
       [8.85702310e-05, 3.24266731e-03, 2.55419797e-02, ...,
        6.22892325e-02, 5.49803551e-03, 9.28008397e-01],
       ...,
       [5.17641791e-02, 3.81715020e-03, 2.96297510e-02, ...,
        2.15667361e-03, 6.49826950e-01, 2.42384687e-05],
       [8.30631310e-04, 6.22003774e-04, 3.14518512e-04, ...,
        1.19366192e-02, 9.71410499e-01, 2.06173648e-04],
       [4.81465717e-05, 4.58821829e-04, 2.15146201e-05, ...,
        5.73434571e-03, 6.96288990e-01, 8.18576980e-02]])

In [14]:
# 关于 np.argmax() 函数的含义与使用
# 对一个一维向量
a = np.array([3, 1, 2, 4, 6, 1])
b = np.argmax(a)#取出a中元素最大值所对应的索引，此时最大值位6，其对应的位置索引值为4，（索引值默认从0开始）
print(b)#4

4


In [15]:
# 对于 2 维向量（通常意义下的矩阵）

a = np.array([[1, 5, 5, 2],
              [9, 6, 2, 8],
              [3, 7, 9, 1]])
b=np.argmax(a, axis=0)#对二维矩阵来讲a[0][1]会有两个索引方向，第一个方向为a[0]，默认按列方向搜索最大值
#a的第一列为1，9，3,最大值为9，所在位置为1，
#a的第一列为5，6，7,最大值为7，所在位置为2，
#此此类推，因为a有4列，所以得到的b为1行4列，
print(b)#[1 2 2 1]
 
c=np.argmax(a, axis=1)#现在按照a[0][1]中的a[1]方向，即行方向搜索最大值，
#a的第一行为1，5，5，2,最大值为5（虽然有2个5，但取第一个5所在的位置），索引值为1，
#a的第2行为9，6，2，8,最大值为9，索引值为0，
#因为a有3行，所以得到的c有3个值，即为1行3列
print(c)#[1 0 2]

[1 2 2 1]
[1 0 2]


In [20]:
# 经过上面 argmax() 函数的预热，大概明白下面就是把神经网络预测的最大值的索引拿出来（得到的概率最大的）
y_pred = np.argmax(a3, axis=1)
y_pred = y_pred + 1 # 又由于数组索引是从 0 开始，为了和现实标签值相对应，进行 +1 处理
y_pred # 预测的值还是在 1 - 10


array([10, 10, 10, ...,  9,  9,  9], dtype=int64)

In [22]:
y == y_pred

array([ True,  True,  True, ...,  True,  True,  True])

In [23]:
acc = np.mean(y_pred == y) #查看准确率有多少
acc

0.9752