In [1]:
# 导入 torch，注意并不是导入 pytorch
import torch

In [2]:
x = torch.arange(12)
x
# x 是一个向量

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 我们可以通过张量的 `shape` 属性来访问张量的形状和张量中元素的总数
x.shape
# 这个维度的长为 12

torch.Size([12])

In [4]:
x.numel()
# 里面元素的总数，永远是个标量

12

In [5]:
# 要改变一个张量的形状而不改变元素数量和元素值，我们可以调用 `reshape` 函数
X = x.reshape(3, 4)
X
# “拧”成一个 3 x 4 的矩阵

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# 我们也可以创建一些元素比较特别的向量
# 使用全 0、全 1、其他常量或者从特定分布中随机采样的数字
torch.zeros((2, 3, 4)) # 可以理解为 2 个 3 行 4 列的二维数组组成的三维数组（元素全是 0）

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# 同理 元素全为 1
torch.ones((2, 3, 4)) # 同理，理解为 2 个 3 行 4 列的二维数组组成的三维数组（元素全是 1）

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# 也可以指定特定值来创建张量
# 通过提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元元素赋予确定值
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) # 使用了一个嵌套列表，这是一个二维的张量

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [9]:
# 如果再加一个括号，就变成三维的
torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [10]:
# 打印他的维数
torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]]).shape
# 其实就是看中括号层数来看张量（数组）是几维的。上面即为三维的，形状为 1 个 3 行 4 列 的数组

torch.Size([1, 3, 4])

### tensor 译为 张量 的意思，张量是任意数组

In [11]:
# 创建张量（数组）之后可以进行一些常见的标准算术运算（+、-、*、/ 和 **）都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x-y, x * y, x / y, x**y, # ** 运算符是求幂运算，即对每个 x 中的元素求 y 元素的 幂次方


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
# 还可以做其他一些运算
# 比如说指数运算
torch.exp(x) # 就是 e 的 x 次方

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [13]:
# 我们也可以把多个张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# 这里的意思是生成 X,Y 这两个张量，并且把这两个张量拼接在一起
# dim=0 表示在 行 合并，dim=1 表示在列合并（dim 如果不写这个参数默认是 0）
# python 计数是从 0 开始，这里是一个二维张量合并，dim=0 就是第一个维度即行，dim=1 即第二个维度即列
# dim 代表沿着此维连接张量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [14]:
# 还可以通过 逻辑运算符构建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
# 对张量中所有元素进行求和会产生一个只有一个元素的张量
X.sum()

tensor(66.)

> **广播机制**|

In [16]:
#即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
# 当两个张量形状不一样，我们可以有办法将两个张量形状变成一样
# 但是前提是这两个张量维度一样，比如 a, b 都是二维的
# 具体可以把 a 的 3 行 1 列中的 1 复制一份，变成 3 x 2
# 把 b 的 1 行 2 列 中的 1 复制 3 分，变成 3 x 2，这样就可以相加了
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
# 再来做一些元素的访问吧！
# 可以用 [-1] 选择最后一个元素，可以用 [1:3] 选择第二个和第三个元素，即 [1:3] = (1,3]
print(X)
X[-1], X[1:3]
# X[-1] 即把最后一行访问出来
# X[1:3] 即把第二行和第三行访问出来

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
# 除读取之外，我们还可以通过指定索引来将元素写入矩阵
X[1, 2] = 9
X
# 表示将 X 中 第一行第二列元素赋值为 9（注意注意 计数从 0 开始，别忘了）

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
# 为多个元素赋值相同的值，我们只需要索引所有元素，然后为他们赋值
X[0:2, :] = 12
X
# 表示将第零行和第一行的所有元素赋值为 12，[0:2] = [0,2)。其他位置元素值不变

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [21]:
# 运行一些操作可能会导致为新结果分配内存
before = id(Y)
Y = Y + X
# 把 Y+X 赋值为 Y，也就是说之前的内存已经被析构掉了
# 内存析构，即销毁原来的变量，释放内存
id(Y) == before
# 新的 Y 的 id 不等于以前的，表示这两个 Y 并不是一样的，新的 Y 系统已经重新分配内存了
# id(object) 表示 object 在 python 里面唯一的标识号，id() 是内存的十进制标识

False

In [22]:
# 如果做原地操作也有办法（也就是说不让系统重新分配内存）
Z  = torch.zeros_like(Y) # 创建一个 Z 张量，元素全是 0 ，且和 Y 的形状和数据类型是一样的
print('id(Z):', id(Z))
Z[:] = X + Y # 再赋值 Z 中所有的元素，令所有元素的值为 X + Y ，其实就是对 Z 中所有元素进行一次改写
print('id(Z):', id(Z))
# 可以看出之前的 Z 和之后的 Z 的 id 是一样的

id(Z): 2702796114944
id(Z): 2702796114944


In [23]:
# 总结一下哈。上面的 Y 操作本质是产生了一个新的 Y
# 而 Z 的操作是对 Z 的元素赋值

In [24]:
# 如果我们在后续计算中没有重复使用 X，我们也可以使用 X[:] = X + Y 或 X += Y 来减少操作的内存开销
before = id(X)
X += Y
id(X) == before
# += 相当于 [:]，操作本质是赋值， X = X + Y 相当于 X 和 Y 加完又给了新创建的 X

True

In [25]:
# 转换为 NumPy 张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [26]:
# 将大小为 1 的张量转换为 Python 标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)
# a.item() 是 numpy 的浮点数


(tensor([3.5000]), 3.5, 3.5, 3)